import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const root = path.dirname(fileURLToPath(import.meta.url));
const out = path.join(root, 'dist');
mkdirSync(out, { recursive: true });
const manifest = JSON.parse(readFileSync(path.join(root, '.openai/hosting.json'), 'utf8'));
const origin = process.env.SITE_URL || '';
const business = 'Sunil Automobile and Electrician & AC';
const address = 'Gandhi Path Rd, Lalarpura, Jaipur, Jaipur Nagar Nigam Area, Rajasthan 302021';
const mapQuery = encodeURIComponent(`${business}, ${address}`);
const maps = `https://www.google.com/maps/search/?api=1&query=${mapQuery}`;
const directions = `https://www.google.com/maps/dir/?api=1&destination=${mapQuery}`;
const icons = {
  pin: '<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',
  wrench: '<path d="M14.7 6.3a5 5 0 0 0-6.4 6.4L3 18a2.1 2.1 0 0 0 3 3l5.3-5.3a5 5 0 0 0 6.4-6.4l-3.3 3.3-3-3Z"/>',
  star: '<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9Z"/>',
  check: '<circle cx="12" cy="12" r="9"/><path d="m8 12 3 3 5-6"/>',
  engine: '<path d="M3 10h3l3-3h7l3 3h2v8h-4l-2 3H7v-3H3Z M9 3h7 M12 3v4 M1 11v6"/>',
  snow: '<path d="M12 2v20 M3.3 7l17.4 10 M3.3 17 20.7 7 M9 4l3 3 3-3 M9 20l3-3 3 3 M3 10l4-1-1-4 M21 14l-4 1 1 4 M6 19l1-4-4-1 M18 5l-1 4 4 1"/>',
  brake: '<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="3"/><path d="M12 3v3 M3 12h3 M12 18v3 M18 12h3"/>',
  bolt: '<path d="m13 2-9 12h7l-1 8 10-13h-7Z"/>',
  battery: '<rect x="3" y="7" width="18" height="14" rx="2"/><path d="M7 7V4h3v3 M14 7V4h3v3 M6 14h4 M16 12v4 M14 14h4"/>',
  oil: '<path d="M12 2S4 11 4 15a8 8 0 1 0 16 0c0-4-8-13-8-13Z M8 15a4 4 0 0 0 4 4"/>',
  car: '<path d="m5 8 2-5h10l2 5 M3 9h18v9H3Z M5 18v3 M19 18v3 M6 12h2 M16 12h2"/>',
  filter: '<rect x="4" y="3" width="16" height="18" rx="2"/><path d="M8 6v12 M12 6v12 M16 6v12"/>',
  clock: '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
  menu: '<path d="M4 6h16 M4 12h16 M4 18h16"/>',
  close: '<path d="m6 6 12 12 M18 6 6 18"/>',
  plus: '<path d="M12 4v16 M4 12h16"/>',
  chevron: '<path d="m9 6 6 6-6 6"/>',
  download: '<path d="M12 3v12 m-5-5 5 5 5-5 M4 16v5h16v-5"/>',
};
const icon = (name, cls = '') => `<svg class="icon ${cls}" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name] || icons.wrench}</svg>`;
const services = [
  ['auto-repair','Auto Repair','Complete automotive repair and maintenance to help keep your vehicle running reliably.','wrench','auto-repair','General repair work','Vehicle inspection','Routine maintenance'],
  ['filters','Air & Cabin Filter Replacement','Air and cabin filter replacement for your engine and interior ventilation.','filter','workshop-service','Air filter replacement','Cabin filter replacement','Ventilation care'],
  ['air-conditioning','Air Conditioning','Automotive AC service to help keep your journeys comfortable.','snow','workshop-service','AC system inspection','Cooling concerns','Climate system service'],
  ['diagnostics','Vehicle Engine Diagnostic','Engine diagnostics to investigate warning lights and running concerns.','engine','engine-detail','Engine warning lights','Running concerns','Diagnostic inspection'],
  ['battery','Battery','Battery service for starting and vehicle power concerns.','battery','vehicle-inspection','Starting concerns','Battery inspection','Vehicle power concerns'],
  ['brakes','Brakes','Brake inspection and maintenance for your vehicle.','brake','engine-detail','Brake inspection','Brake maintenance','Braking concerns'],
  ['electrical','Electrical','Automotive electrical service for vehicle systems and electrical faults.','bolt','vehicle-inspection','Electrical inspection','Fault investigation','Vehicle electrical systems'],
  ['oil-change','Oil Change','Vehicle oil changes as part of regular engine maintenance.','oil','auto-repair','Engine oil change','Routine engine care','Maintenance enquiry'],
  ['suspension','Steering & Suspension Repair','Repair for steering and suspension concerns, handling and ride comfort.','car','mechanic-engine','Steering concerns','Suspension inspection','Ride and handling'],
  ['transmission','Transmission','Service and repair enquiries for transmission-related concerns.','engine','mechanic-engine','Transmission concerns','Gear change issues','Service enquiries'],
];
const img = (name, alt, attrs = '') => `<img src="/assets/${name}.webp" alt="${alt}" width="1000" height="667" loading="lazy" decoding="async" ${attrs}>`;
const btn = (href, text, type = '', external = false) => `<a class="button ${type}" href="${href}"${external ? ' target="_blank" rel="noopener noreferrer"' : ''}>${text}</a>`;
const dirButton = (type = '') => btn(directions, `${icon('pin')}Get Directions`, type, true);
const eyebrow = text => `<p class="eyebrow">${text}</p>`;
const logo = `<span class="brand-mark">${icon('wrench')}</span><span class="brand-wordmark">SUNIL AUTOMOBILE<span>and Electrician & AC</span></span>`;
const nav = [['/','Home'],['/services/','Services'],['/about/','About'],['/gallery/','Gallery'],['/#reviews','Reviews'],['/location/','Location'],['/contact/','Contact']];
function header(route) {
  return `<header class="site-header"><div class="header-inner"><a class="brand" href="/" aria-label="Sunil Automobile home">${logo}</a><nav class="desktop-nav" aria-label="Main navigation">${nav.map(([href,label])=>`<a href="${href}"${route===href?' class="active" aria-current="page"':''}>${label}</a>`).join('')}</nav><div class="header-actions">${dirButton('button-small')}<button class="menu-toggle" type="button" aria-label="Open navigation" aria-expanded="false" aria-controls="mobile-nav">${icon('menu')}</button></div></div><nav id="mobile-nav" class="mobile-nav" aria-label="Mobile navigation" hidden>${nav.map(([href,label])=>`<a href="${href}"${route===href?' aria-current="page"':''}>${label}</a>`).join('')}</nav><div class="scroll-progress" aria-hidden="true"></div></header>`;
}
function footer() {
  return `<footer class="site-footer"><div class="container footer-grid"><div><a class="brand" href="/">${logo}</a><p>Automotive repair, electrical & AC.<br>Your neighbourhood workshop in Jaipur.</p><a href="${maps}" target="_blank" rel="noopener noreferrer" class="footer-address">${icon('pin')} Lalarpura, Jaipur, Rajasthan</a></div><div><h3>Explore</h3>${nav.filter(([,l])=>l!=='Reviews').map(([h,l])=>`<a href="${h}">${l}</a>`).join('')}</div><div><h3>Our Services</h3>${services.slice(0,5).map(s=>`<a href="/services/#${s[0]}">${s[1]}</a>`).join('')}</div><div><h3>Vehicle Care</h3>${services.slice(5).map(s=>`<a href="/services/#${s[0]}">${s[1]}</a>`).join('')}</div></div><div class="container footer-bottom"><p>© 2026 ${business}. All rights reserved.</p><span>Gandhi Path Road · Jaipur</span><a href="#top">Back to top ${icon('chevron')}</a></div></footer>`;
}
function pageHero(label,title,desc,image='auto-repair',extra='') {
  return `<section class="page-hero"><div class="page-hero-image">${img(image,'Automotive service detail')}</div><div class="container">${eyebrow(label)}<h1>${title}</h1><p>${desc}</p>${extra}</div><span class="hero-index" aria-hidden="true">SUNIL / AUTOMOTIVE CARE</span></section>`;
}
function trust() {
  return `<section class="trust-strip" aria-label="Business information"><div class="container trust-grid">${[['star','3.7 <span>/ 5</span>','Google Rating'],['check','3 Reviews','Google Reviews'],['wrench','10','Core Services'],['pin','Lalarpura','Jaipur, Rajasthan']].map(([i,n,l])=>`<div class="trust-item">${icon(i)}<div><strong>${n}</strong><span>${l}</span></div></div>`).join('')}</div></section>`;
}
function featured() {
  return `<section class="featured-section container" aria-label="Featured services"><div class="featured-grid">${[
    ['diagnostics','Engine Diagnostics','Understand what your engine is telling you.','engine-detail','01 / PRECISION'],
    ['air-conditioning','Air Conditioning','Comfort for every kilometre.','workshop-service','02 / COMFORT'],
    ['suspension','Brakes & Suspension','Care for the way your vehicle moves.','vehicle-inspection','03 / CONTROL'],
  ].map(([id,title,text,image,label])=>`<a class="feature-panel reveal" href="/services/#${id}">${img(image,`${title} automotive detail`)}<div class="feature-content"><span class="eyebrow">${label}</span><h3>${title}</h3><p>${text}</p><span class="text-link">Explore service ${icon('plus')}</span></div></a>`).join('')}</div></section>`;
}
function processSection() {
  return `<section class="section process-section"><div class="container"><div class="section-heading reveal"><div>${eyebrow('THE WAY WE WORK')}<h2>A little care.<br>A better journey.</h2></div><p>From your first visit to getting back on the road.<br>Four straightforward steps.</p></div><ol class="process-grid reveal">${[['pin','Visit','Bring your vehicle to our workshop.'],['engine','Inspect','Discuss the concern and inspect your vehicle.'],['wrench','Service','Get the required service for your vehicle.'],['car','Back on the Road','Continue your journey with your vehicle cared for.']].map(([i,t,d],n)=>`<li><span class="step-icon">${icon(i)}</span><span class="step-number">0${n+1}</span><h3>${t}</h3><p>${d}</p></li>`).join('')}</ol></div></section>`;
}
function reviews() {
  return `<section id="reviews" class="section review-section"><div class="container review-grid"><div class="reveal">${eyebrow('CUSTOMER VOICES')}<h2>Small workshop.<br>Real feedback.</h2><p>Google review information supplied for Sunil Automobile.</p><a class="text-link" href="${maps}" target="_blank" rel="noopener noreferrer">View the current Google listing ${icon('plus')}</a></div><div class="review-summary reveal"><span class="google-g" aria-hidden="true">G</span><div><strong class="review-score">3.7<span>/ 5</span></strong><p>Based on 3 Google reviews</p></div><div class="rating-stars" aria-label="3.7 out of 5 stars"><span>★★★★★</span>★★★★★</div><blockquote>“Good service and staff very s...”</blockquote><span class="small muted">Supplied review excerpt · original text is truncated</span></div></div></section>`;
}
function location(full = false) {
  return `<section id="location" class="section location-section"><div class="container">${full?'':`<div class="section-heading reveal"><div>${eyebrow('RIGHT HERE IN JAIPUR')}<h2>Easy to find.<br>Ready for your visit.</h2></div><p>Find us on Gandhi Path Road,<br>in the heart of Lalarpura.</p></div>`}<div class="location-grid reveal"><div class="map-wrap"><iframe title="Map showing Sunil Automobile in Lalarpura, Jaipur" src="https://maps.google.com/maps?q=${mapQuery}&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=&amp;output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe><a class="map-external" href="${maps}" target="_blank" rel="noopener noreferrer">${icon('pin')} Open in Google Maps</a></div><div class="location-details"><span class="location-icon">${icon('pin')}</span>${eyebrow('COME SAY HELLO')}<h3>Find us in Lalarpura.</h3><address>${address}</address><p class="hours">${icon('clock')} Listing hours: closes 8 PM</p><p class="small muted">Supplied listing: “Open · Closes 8 PM”. Please check Google Maps for current hours before visiting.</p>${dirButton()}<span class="small muted">Directions open in Google Maps.</span></div></div></div></section>`;
}
function finalCta() {
  return `<section class="final-cta"><div class="final-image">${img('hero-workshop','Automotive workshop interior')}</div><div class="container final-inner reveal"><div>${eyebrow('FOR EVERY JOURNEY AHEAD')}<h2>Keep your<br>vehicle moving.</h2><p>Visit Sunil Automobile and Electrician & AC<br>in Lalarpura, Jaipur.</p></div><div class="button-group">${dirButton()}${btn('/contact/','Send Enquiry','button-outline')}</div></div></section>`;
}
const galleryItems = [
  ['hero-workshop','Workshop','Workshop interior and engine service','workshop'],
  ['auto-repair','Hands-on care','Hands working on a vehicle engine','service'],
  ['engine-detail','Under the hood','Close-up automotive engine components','details'],
  ['workshop-service','Vehicle service','Mechanic inspecting a vehicle under the hood','service'],
  ['mechanic-engine','Engine maintenance','Engine being serviced in a workshop','workshop'],
  ['vehicle-inspection','The details matter','Vehicle engine inspection and maintenance','details'],
];
function galleryGrid(limit=6) {
  return `<div class="gallery-grid">${galleryItems.slice(0,limit).map(([image,title,alt,cat],n)=>`<button class="gallery-item reveal" type="button" data-category="${cat}" data-gallery-index="${n}" data-image="/assets/${image}.webp" data-caption="${title}" aria-label="View ${alt}">${img(image,alt)}<span class="gallery-caption">${title} ${icon('plus')}</span></button>`).join('')}</div>`;
}
function lightbox() {
  return `<dialog id="lightbox" class="lightbox" aria-labelledby="lightbox-caption"><button class="lightbox-close" type="button" aria-label="Close image">${icon('close')}</button><button class="lightbox-prev" type="button" aria-label="Previous image">${icon('chevron')}</button><figure><img id="lightbox-image" alt="" width="1000" height="667"><figcaption id="lightbox-caption"></figcaption></figure><button class="lightbox-next" type="button" aria-label="Next image">${icon('chevron')}</button></dialog>`;
}
function home() {
  return `<section class="hero"><div class="hero-visual"><img src="/assets/auto-repair.webp" srcset="/assets/auto-repair.webp 1000w" sizes="(max-width: 767px) 100vw, 70vw" alt="A mechanic carefully working on a vehicle engine" width="1000" height="1500" fetchpriority="high" decoding="async"></div><div class="hero-shade"></div><div class="container hero-content">${eyebrow('AUTO REPAIR <span>·</span> ELECTRICAL <span>·</span> AC')}<h1><span>Complete Care</span><span>for Your <em>Vehicle.</em></span></h1><p>Automotive repair, diagnostics, AC, electrical<br class="desktop-break"> and maintenance services in Lalarpura, Jaipur.</p><div class="button-group">${dirButton()}${btn('/services/','Explore Services','button-outline')}</div><a class="hero-location" href="/location/">${icon('pin')} Lalarpura, Jaipur</a></div><div class="hero-bottom"><span>AUTOMOTIVE CARE. PERSONAL ATTENTION.</span><a href="#services">SCROLL TO EXPLORE <span class="scroll-line"></span></a></div></section>${trust()}
  <section id="services" class="section"><div class="container home-services"><div class="services-intro reveal">${eyebrow('OUR SERVICES')}<h2>Automotive<br>services.<br><em>Done right.</em></h2><p>From everyday maintenance to engine diagnostics and repair. Care for the systems that keep you moving.</p><a class="text-link" href="/services/">Explore all 10 services ${icon('plus')}</a></div><div class="service-tile-grid">${[services[0],services[2],services[3],services[4],services[5],services[6],services[7],services[9]].map(s=>`<a class="service-tile reveal" href="/services/#${s[0]}"><div class="service-tile-image">${img(s[4],`${s[1]} service detail`)}<span class="service-tile-icon">${icon(s[3])}</span></div><h3>${s[1]==='Vehicle Engine Diagnostic'?'Engine Diagnostics':s[1]} ${icon('plus')}</h3></a>`).join('')}</div></div></section>${featured()}
  <section class="section about-preview"><div class="container split-section"><div class="about-image reveal">${img('workshop-service','Hands-on automotive inspection')}<span class="image-label">PRECISION IN EVERY DETAIL</span></div><div class="reveal">${eyebrow('YOUR NEIGHBOURHOOD WORKSHOP')}<h2>More than a repair.<br>Care for your journey.</h2><p>At Sunil Automobile and Electrician & AC, vehicle care brings together repair, diagnostics, electrical services and air conditioning.</p><p>Find the service you need, tell us what your vehicle needs, and visit our workshop in Lalarpura, Jaipur.</p>${btn('/about/','Get to Know Us','button-dark')}</div></div></section>${processSection()}
  <section class="section gallery-section"><div class="container"><div class="section-heading reveal"><div>${eyebrow('A CLOSER LOOK')}<h2>The work.<br>The care. The details.</h2></div><a class="text-link" href="/gallery/">Explore the gallery ${icon('plus')}</a></div>${galleryGrid(3)}<p class="image-disclaimer">Illustrative automotive photography. Original workshop photos can be added here.</p></div></section>${reviews()}${location()}${finalCta()}${lightbox()}`;
}
function servicesPage() {
  return `${pageHero('OUR SERVICES','Professional automotive<br>services for every need.','From routine maintenance to diagnostics and repair. Explore our ten core automotive services.','auto-repair')}
  <section class="section service-selector-section"><div class="container"><div class="service-filter" aria-label="Service categories">${[['all','All Services'],['auto-repair','Auto Repair'],['air-conditioning','AC Service'],['diagnostics','Diagnostics'],['electrical','Electrical'],['brakes','Brakes']].map(([id,t],n)=>`<button type="button" data-service-shortcut="${id}" class="${n===0?'active':''}" aria-pressed="${n===0}">${t}</button>`).join('')}</div><div class="service-selector"><div class="service-list" aria-label="Select a service">${services.map((s,n)=>`<button type="button" class="service-option ${n===0?'selected':''}" data-service="${s[0]}" aria-pressed="${n===0}" aria-controls="service-detail"><span class="service-option-image">${img(s[4],`${s[1]} detail`)}</span><span class="service-number">${String(n+1).padStart(2,'0')}</span><span><strong>${s[1]}</strong><small>${s[2]}</small></span>${icon('chevron')}</button>`).join('')}</div><article id="service-detail" class="service-detail" aria-live="polite"><div class="service-detail-image">${img('auto-repair','Auto repair engine inspection','id="service-image"')}<span id="service-icon" class="detail-icon">${icon('wrench')}</span><span class="scan-line" aria-hidden="true"></span></div><div class="service-detail-content"><span id="service-detail-number" class="eyebrow">01 / VEHICLE CARE</span><h2 id="service-title">Auto Repair</h2><p id="service-description">${services[0][2]}</p><ul id="service-points">${services[0].slice(5).map(p=>`<li>${icon('check')}${p}</li>`).join('')}</ul>${btn('/contact/?service=auto-repair','Enquire About This Service','','false'===true).replace('class="button ','id="service-enquiry" class="button ')}<p class="small muted">Discuss your vehicle’s specific needs at the workshop.</p></div></article></div><noscript><div class="noscript-services">${services.map(s=>`<article id="${s[0]}"><h2>${s[1]}</h2><p>${s[2]}</p>${btn('/contact/','Enquire About Service')}</article>`).join('')}</div></noscript></div></section>
  <section class="section expertise-section"><div class="container"><div class="section-heading reveal"><div>${eyebrow('UNDERSTANDING WHAT’S INSIDE')}<h2>Every system.<br>One place for care.</h2></div><p>Your vehicle works as a connected whole.<br>Explore the care behind the journey.</p></div><div class="expertise-grid">${[['engine','Diagnostics','See what the machine is telling you.','scan'],['snow','Climate','Comfort is part of the journey.','airflow'],['bolt','Electrical','Care for the connections that power your vehicle.','electric']].map(([i,t,d,cl])=>`<a class="expertise-item reveal ${cl}" href="/services/#${t==='Diagnostics'?'diagnostics':t==='Climate'?'air-conditioning':'electrical'}"><div class="system-visual">${icon(i)}<span class="system-line"></span></div><h3>${t}</h3><p>${d}</p></a>`).join('')}</div></div></section>${finalCta()}<script type="application/json" id="service-data">${JSON.stringify(services.map((s,n)=>({id:s[0],title:s[1],description:s[2],icon:icon(s[3]),image:s[4],points:s.slice(5),number:n+1})))}</script>`;
}
function aboutPage() {
  return `${pageHero('ABOUT US','Committed to keeping<br>your vehicle in top shape.','Automotive repair, diagnostics, AC and electrical services, right here in Lalarpura, Jaipur.','workshop-service')}${trust()}<section class="section"><div class="container split-section"><div class="reveal">${eyebrow('SUNIL AUTOMOBILE')}<h2>Vehicle care.<br>Close to home.</h2><p>Sunil Automobile and Electrician & AC is an auto repair shop on Gandhi Path Road in Lalarpura, Jaipur.</p><p>Our services cover auto repair, engine diagnostics, AC, electrical, battery, brakes, oil changes, filter replacement, steering and suspension, and transmission.</p><p>Whether you have a particular concern or need routine maintenance, start by exploring our services.</p>${btn('/services/','Explore Our Services')}</div><div class="about-image reveal">${img('auto-repair','Mechanic working carefully on automotive components')}<span class="image-label">CARE FOR THE ROAD AHEAD</span></div></div></section><section class="section care-section"><div class="container"><div class="section-heading reveal"><div>${eyebrow('BUILT AROUND YOUR VEHICLE')}<h2>One workshop.<br>Connected care.</h2></div><p>From the engine to the cabin,<br>find care for your vehicle’s key systems.</p></div><div class="care-grid">${[['wrench','Repair & Maintenance','General vehicle repair, oil changes and routine care.'],['engine','Engine & Electrical','Diagnostics, battery and automotive electrical services.'],['snow','Cabin Comfort','Air conditioning and automotive filter replacement.'],['brake','Ride & Control','Brakes, steering, suspension and transmission services.']].map(([i,t,d])=>`<div class="care-item reveal">${icon(i)}<h3>${t}</h3><p>${d}</p></div>`).join('')}</div></div></section>${processSection()}${reviews()}${finalCta()}`;
}
function galleryPage() {
  return `${pageHero('THE GALLERY','The details behind<br>every journey.','A closer look at automotive care, workshop life and the systems that keep vehicles moving.','engine-detail')}<section class="section"><div class="container"><div class="gallery-filters" aria-label="Filter gallery">${[['all','All'],['workshop','Workshop'],['service','Service'],['details','Details']].map(([id,t],n)=>`<button type="button" data-gallery-filter="${id}" class="${n===0?'active':''}" aria-pressed="${n===0}">${t}</button>`).join('')}</div>${galleryGrid()}<p class="image-disclaimer">Illustrative automotive photography, sourced from Pexels. These images do not depict the Sunil Automobile workshop.</p></div></section>${finalCta()}${lightbox()}`;
}
function locationPage() {
  return `${pageHero('OUR LOCATION','Find us in Lalarpura.','Visit our workshop on Gandhi Path Road, Lalarpura, Jaipur. Your next service starts here.','hero-workshop')}${location(true)}<section class="section location-note"><div class="container split-section"><div class="reveal">${eyebrow('PLAN YOUR VISIT')}<h2>A familiar road.<br>A local workshop.</h2><p>Use Google Maps for the quickest route from your location. Check the current listing for opening hours before setting off.</p>${dirButton()}</div><div class="visit-checklist reveal"><h3>Before you visit</h3><p>${icon('check')} Note any warning lights or unusual symptoms.</p><p>${icon('check')} Bring your vehicle details.</p><p>${icon('check')} Tell us which service you need.</p><a class="text-link" href="/contact/">Prepare a service enquiry ${icon('plus')}</a></div></div></section>${finalCta()}`;
}
function enquiryForm() {
  return `<form id="enquiry-form"><div class="form-heading"><h2>Service Enquiry</h2><p>Tell us a little about your vehicle.</p></div><p class="form-notice">Online enquiry delivery is not connected yet. You can prepare and download your enquiry to share at the workshop.</p><div class="form-grid"><label for="name">Name <span>*</span><input id="name" name="name" placeholder="Your name" autocomplete="name" minlength="2" maxlength="100" required></label><label for="phone">Phone <span>*</span><input id="phone" name="phone" type="tel" placeholder="Your phone number" autocomplete="tel" inputmode="tel" pattern="[+0-9 ]{10,18}" maxlength="18" title="Enter a phone number with 10–15 digits" required></label><label for="vehicle">Vehicle <span>*</span><input id="vehicle" name="vehicle" placeholder="e.g. Maruti Swift" maxlength="100" required></label><label for="service">Service <span>*</span><select id="service" name="service" required><option value="">Select a service</option>${services.map(s=>`<option value="${s[0]}">${s[1]}</option>`).join('')}</select></label><label for="message" class="full-width">Message<textarea id="message" name="message" rows="4" maxlength="2000" placeholder="Tell us more about your vehicle or service request..."></textarea></label></div><p class="small muted">Your details stay in this browser until you download them.</p><button type="submit" class="button form-submit" disabled>Prepare Enquiry ${icon('check')}</button><noscript><p>Enable JavaScript to prepare an enquiry, or visit the workshop directly.</p></noscript><div id="form-result" class="form-result" role="status" hidden><h3>Your enquiry is ready.</h3><p>It has not been sent. Download a copy to share when you visit the workshop.</p><button id="download-enquiry" class="button button-dark" type="button">${icon('download')} Download Enquiry</button></div></form>`;
}
function contactPage() {
  return `${pageHero('GET IN TOUCH','Need your vehicle checked?','Prepare a service enquiry, or find directions to our workshop in Lalarpura, Jaipur.','auto-repair')}<section class="section contact-section"><div class="container contact-layout"><div class="contact-image reveal">${img('auto-repair','Vehicle engine repair detail')}<div><span class="eyebrow">LET’S TALK VEHICLE CARE</span><h3>Every journey<br>starts with care.</h3></div></div><div class="reveal">${enquiryForm()}</div><aside class="contact-aside reveal"><h3>Our Services</h3><ul>${services.map(s=>`<li>${icon('check')}${s[1]}</li>`).join('')}</ul><div class="contact-address"><span class="eyebrow">VISIT THE WORKSHOP</span><p>${icon('pin')} Gandhi Path Rd,<br>Lalarpura, Jaipur<br>Rajasthan 302021</p>${dirButton('button-small')}</div></aside></div></section>`;
}
const pages = [
  ['/', 'Auto Repair, Electrical & AC in Lalarpura, Jaipur', 'Sunil Automobile and Electrician & AC offers auto repair, engine diagnostics, AC, electrical, brakes and maintenance in Lalarpura, Jaipur. Find services and directions.', home],
  ['/services/', 'Automotive Services in Jaipur', 'Explore all 10 services at Sunil Automobile, Lalarpura, Jaipur: auto repair, diagnostics, AC, electrical, brakes, battery, oil, filters, suspension and transmission.', servicesPage],
  ['/about/', 'About Our Auto Repair Workshop in Jaipur', 'Learn about Sunil Automobile and Electrician & AC, an automotive repair shop on Gandhi Path Road in Lalarpura, Jaipur, Rajasthan.', aboutPage],
  ['/gallery/', 'Automotive Service Gallery', 'Explore automotive repair and maintenance photography illustrating vehicle care, engine systems and workshop service.', galleryPage],
  ['/location/', 'Location & Directions · Lalarpura, Jaipur', 'Find Sunil Automobile and Electrician & AC on Gandhi Path Road, Lalarpura, Jaipur, Rajasthan 302021. Open Google Maps for directions to the workshop.', locationPage],
  ['/contact/', 'Service Enquiry · Sunil Automobile Jaipur', 'Prepare an enquiry for auto repair, engine diagnostics, air conditioning or electrical services at Sunil Automobile in Lalarpura, Jaipur.', contactPage],
];
const escape = s => s.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
for (const [route,title,desc,content] of pages) {
  const canonical = origin ? origin.replace(/\/$/,'')+route : '';
  const schema = {'@context':'https://schema.org','@type':'AutoRepair',name:business,description:'Automotive repair, electrical and AC services in Lalarpura, Jaipur.',address:{'@type':'PostalAddress',streetAddress:'Gandhi Path Rd, Lalarpura',addressLocality:'Jaipur',addressRegion:'Rajasthan',postalCode:'302021',addressCountry:'IN'},hasMap:maps,areaServed:{'@type':'City',name:'Jaipur'},...(origin?{url:origin}:{}),hasOfferCatalog:{'@type':'OfferCatalog',name:'Automotive services',itemListElement:services.map(s=>({'@type':'Offer',itemOffered:{'@type':'Service',name:s[1]}}))}};
  const html = `<!doctype html><html lang="en-IN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(title)} | Sunil Automobile</title><meta name="description" content="${escape(desc)}"><meta name="theme-color" content="#ffffff"><meta name="robots" content="index,follow"><meta property="og:type" content="website"><meta property="og:locale" content="en_IN"><meta property="og:site_name" content="Sunil Automobile"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(desc)}">${canonical?`<link rel="canonical" href="${canonical}"><meta property="og:url" content="${canonical}">`:''}<link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="stylesheet" href="/assets/style.css"><link rel="preload" href="/assets/manrope-latin.woff2" as="font" type="font/woff2" crossorigin>${route==='/'?'<link rel="preload" href="/assets/auto-repair.webp" as="image">':''}<script type="application/ld+json">${JSON.stringify(schema)}</script><script src="/assets/app.js" defer></script></head><body id="top" data-page="${route}"><a href="#main" class="skip-link">Skip to content</a>${header(route)}<main id="main">${content()}</main>${footer()}</body></html>`;
  const dir = path.join(out, route === '/' ? '' : route.slice(1));
  mkdirSync(dir, {recursive:true});
  writeFileSync(path.join(dir,'index.html'), html);
}
for (const file of ['style.css','app.js']) copyFileSync(path.join(root,'src',file),path.join(out,'assets',file));
writeFileSync(path.join(out,'favicon.svg'),'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="7" fill="#ed171f"/><path d="M22 7a7 7 0 0 0-9 9l-6 6 3 3 6-6a7 7 0 0 0 9-9l-4 4-3-3Z" fill="white"/></svg>');
writeFileSync(path.join(out,'robots.txt'),`User-agent: *\nAllow: /\n${origin?`Sitemap: ${origin.replace(/\/$/,'')}/sitemap.xml\n`:''}`);
if(origin) writeFileSync(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.map(([route])=>`<url><loc>${escape(origin.replace(/\/$/,'')+route)}</loc></url>`).join('')}</urlset>`);
console.log(`Built ${pages.length} static pages. ${origin?'Canonical URLs and sitemap included.':'Set SITE_URL to add production canonical URLs and sitemap.'} Site identity: ${manifest.project_id || 'local'}`);
